"""Bounded pure ATR-v0.1 typed-relation representation."""

from .contracts import (
    CANONICAL_PROFILE,
    HARD_MAX_CANONICAL_INPUT_BYTES,
    HARD_MAX_STRING_BYTES,
    HARD_MAX_TUPLE_ITEMS,
    INPUT_FINGERPRINT_DOMAIN,
    TYPED_RELATION_CONTRACT_VERSION,
    AnchoredTypedRelationRecord,
    ClaimAnchor,
    RelationEndpoints,
    RelationOrientation,
    RelationOrigin,
    RelationProvenance,
    RelationRepresentationBudget,
    RelationScope,
    RelationSemantics,
    RelationType,
    ScopeReference,
    ScopeReferenceKind,
    TypedRelationBudgetExceeded,
    TypedRelationContractError,
)
from .representation import represent_typed_relation

__all__ = [
    "CANONICAL_PROFILE",
    "HARD_MAX_CANONICAL_INPUT_BYTES",
    "HARD_MAX_STRING_BYTES",
    "HARD_MAX_TUPLE_ITEMS",
    "INPUT_FINGERPRINT_DOMAIN",
    "TYPED_RELATION_CONTRACT_VERSION",
    "AnchoredTypedRelationRecord",
    "ClaimAnchor",
    "RelationEndpoints",
    "RelationOrientation",
    "RelationOrigin",
    "RelationProvenance",
    "RelationRepresentationBudget",
    "RelationScope",
    "RelationSemantics",
    "RelationType",
    "ScopeReference",
    "ScopeReferenceKind",
    "TypedRelationBudgetExceeded",
    "TypedRelationContractError",
    "represent_typed_relation",
]
