"""Explicit P0 storage, trusted-write, batch, and idempotency primitives."""

from .atomic_batch import (
    BatchAppendReceipt,
    BatchEntry,
    BatchInvariantError,
    SQLiteAtomicBatchAppender,
)
from .budget import ResourceBudgetExceeded, VerificationBudget
from .concurrency import (
    DEFAULT_BUSY_RETRY_POLICY,
    BusyRetryPolicy,
    StoreBusyError,
    VersionConflictError,
)
from .integrity import (
    IntegrityCode,
    IntegrityFailure,
    R0IntegrityReport,
    R0IntegrityVerifier,
)
from .redaction import (
    REDACTION_EVENT_TYPE,
    REDACTION_IDEMPOTENCY_PROFILE,
    REDACTION_PAYLOAD_SCHEMA,
    CrossStreamRedactionError,
    RedactionConflictError,
    RedactionError,
    RedactionRequest,
    RedactionResult,
    RedactionStatus,
    SQLiteRedactionExecutor,
    TargetAlreadyRedactedError,
    TargetEventNotFoundError,
    TargetPayloadMissingError,
    redacted_targets_for_stream,
    redaction_fingerprint,
    redaction_payload_value,
)
from .sealing import (
    compute_event_hash,
    compute_payload_digest,
    seal_event,
    seal_event_bytes,
    validate_event_for_commit,
)
from .stream_meta import GENESIS_HASH, StreamMeta
from .idempotency import (
    IDEMPOTENCY_PROFILE,
    IdempotencyConflictError,
    IdempotencyInvariantError,
    IdempotencyReceiptIntegrityError,
    IdempotencyStatus,
    IdempotentAppendResult,
    IdempotentBatchRequest,
    SQLiteIdempotentBatchAppender,
    idempotency_fingerprint,
)
from .sqlite_store import (
    MINIMUM_SQLITE_VERSION,
    SCHEMA_VERSION,
    SQLiteEventPayloadStore,
    StorageError,
    StoredPayload,
    StoreNotInitializedError,
    ensure_supported_sqlite_runtime,
)

__all__ = [
    "DEFAULT_BUSY_RETRY_POLICY",
    "GENESIS_HASH",
    "IntegrityCode",
    "IntegrityFailure",
    "R0IntegrityReport",
    "R0IntegrityVerifier",
    "REDACTION_EVENT_TYPE",
    "REDACTION_IDEMPOTENCY_PROFILE",
    "REDACTION_PAYLOAD_SCHEMA",
    "CrossStreamRedactionError",
    "RedactionConflictError",
    "RedactionError",
    "RedactionRequest",
    "RedactionResult",
    "RedactionStatus",
    "SQLiteRedactionExecutor",
    "TargetAlreadyRedactedError",
    "TargetEventNotFoundError",
    "TargetPayloadMissingError",
    "redacted_targets_for_stream",
    "redaction_fingerprint",
    "redaction_payload_value",
    "ResourceBudgetExceeded",
    "StreamMeta",
    "VerificationBudget",
    "IDEMPOTENCY_PROFILE",
    "BusyRetryPolicy",
    "BatchAppendReceipt",
    "BatchEntry",
    "BatchInvariantError",
    "IdempotencyConflictError",
    "IdempotencyInvariantError",
    "IdempotencyReceiptIntegrityError",
    "IdempotencyStatus",
    "IdempotentAppendResult",
    "IdempotentBatchRequest",
    "MINIMUM_SQLITE_VERSION",
    "SCHEMA_VERSION",
    "SQLiteAtomicBatchAppender",
    "SQLiteEventPayloadStore",
    "SQLiteIdempotentBatchAppender",
    "StorageError",
    "StoredPayload",
    "StoreBusyError",
    "StoreNotInitializedError",
    "VersionConflictError",
    "compute_event_hash",
    "compute_payload_digest",
    "seal_event",
    "seal_event_bytes",
    "validate_event_for_commit",
    "ensure_supported_sqlite_runtime",
    "idempotency_fingerprint",
]
